# Generated by Django 5.2.17 on 2026-09-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0002_affiliatecategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover', models.ImageField(upload_to='stories/cover/')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='StorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories/slides/')),
                ('alt_text', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='stories.story')),
            ],
            options={
                'verbose_name': 'slide de story',
                'verbose_name_plural': 'slides de story',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('title', 'Título'), ('text', 'Texto'), ('badge', 'Destaque'), ('cta', 'Botão')], default='text', max_length=20, verbose_name='tipo')),
                ('text', models.CharField(blank=True, help_text='Texto exibido sobre a imagem. Deixe vazio para botões.', max_length=300, verbose_name='texto')),
                ('variant', models.CharField(choices=[('accent', 'Destaque'), ('light', 'Claro')], default='light', max_length=20, verbose_name='variante visual')),
                ('position', models.CharField(choices=[('top', 'Superior'), ('center', 'Centro'), ('bottom', 'Inferior')], default='center', max_length=20, verbose_name='posição')),
                ('animation', models.CharField(choices=[('fade-up', 'Aparecer de baixo'), ('fade', 'Aparecer'), ('none', 'Sem animação')], default='fade-up', max_length=20, verbose_name='animação')),
                ('delay_ms', models.PositiveIntegerField(default=0, help_text='Atraso antes da animação, em milissegundos.', verbose_name='atraso (ms)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate_partner', models.ForeignKey(blank=True, help_text='Usado quando o elemento for um botão de afiliado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_elements', to='affiliates.affiliatepartner', verbose_name='parceiro afiliado')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='stories.storyslide', verbose_name='slide')),
            ],
            options={
                'verbose_name': 'elemento de story',
                'verbose_name_plural': 'elementos de story',
                'ordering': ('order', 'id'),
            },
        ),
    ]
