# Generated by Django 5.2.17 on 2026-09-16 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='variant',
            field=models.CharField(default='#D96C43', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor'),
        ),
    ]
