# Generated by Django 5.2.17 on 2026-09-16 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_storyelement_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor de fundo'),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='variant',
            field=models.CharField(default='#D96C43', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor do texto'),
        ),
    ]
