# Generated by Django 5.2.17 on 2026-09-18 17:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storyelement_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='font_size_rem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o tamanho padrão.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='tamanho da fonte (rem)'),
        ),
    ]
