# Generated by Django 5.2.17 on 2026-09-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_storyelement_font_size_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='font_weight',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(100, 'Thin (100)'), (200, 'Extra Light (200)'), (300, 'Light (300)'), (400, 'Regular (400)'), (500, 'Medium (500)'), (600, 'Semi Bold (600)'), (700, 'Bold (700)'), (800, 'Extra Bold (800)'), (900, 'Black (900)')], help_text='Deixe vazio para usar o peso padrão do tipo.', null=True, verbose_name='peso da fonte'),
        ),
    ]
