# Generated by Django 5.2.17 on 2026-09-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_storyelement_font_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='font_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Itálico')], default='normal', max_length=10, verbose_name='estilo da fonte'),
        ),
    ]
