# Generated by Django 5.2.17 on 2026-09-19 12:48

from django.db import migrations


def migrate_animation_values(apps, schema_editor):
    StoryElement = apps.get_model("stories", "StoryElement")

    replacements = {
        "fade": "fade-in",
        "fade-up": "fly-in-bottom",
        "fade-left": "fly-in-left",
    }

    for old_value, new_value in replacements.items():
        StoryElement.objects.filter(
            animation=old_value,
        ).update(
            animation=new_value,
        )


def reverse_animation_values(apps, schema_editor):
    StoryElement = apps.get_model("stories", "StoryElement")

    replacements = {
        "fade-in": "fade",
        "fly-in-bottom": "fade-up",
        "fly-in-left": "fade-left",
    }

    for new_value, old_value in replacements.items():
        StoryElement.objects.filter(
            animation=new_value,
        ).update(
            animation=old_value,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0006_storyelement_font_style"),
    ]

    operations = [
        migrations.RunPython(
            migrate_animation_values,
            reverse_animation_values,
        ),
    ]
