# Generated by Django 5.2.17 on 2026-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_migrate_animation_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='animation',
            field=models.CharField(choices=[('none', 'Sem animação'), ('fade-in', 'Aparecer'), ('fly-in-bottom', 'Aparecer de baixo'), ('fly-in-top', 'Aparecer de cima'), ('fly-in-left', 'Aparecer da esquerda'), ('fly-in-right', 'Aparecer da direita'), ('scale-fade-up', 'Aparecer aumentando'), ('zoom-in', 'Aproximar')], default='fly-in-bottom', max_length=20, verbose_name='animação'),
        ),
    ]
