# Generated by Django 5.2.17 on 2026-09-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_excerpt'),
        ('stories', '0008_alter_storyelement_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Usado quando o elemento for um botão de post relacionado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_elements', to='blog.post', verbose_name='post relacionado'),
        ),
    ]
