# Generated by Django 5.2.17 on 2026-09-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_storyelement_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0, help_text='Duração da animação, em milissegundos.', verbose_name='duração (ms)'),
        ),
    ]
