# Generated by Django 5.2.17 on 2026-09-20 20:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_alter_storyelement_duration_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyslide',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor do texto'),
        ),
        migrations.AlterField(
            model_name='storyelement',
            name='font_size_rem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o tamanho padrão.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='tamanho da fonte (rem)'),
        ),
    ]
