# Generated by Django 5.2.17 on 2026-09-21 11:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_storyslide_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyelement',
            name='gap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o tamanho padrão de 0.4rem.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9.00'))], verbose_name='tamanho do gap abaixo do elemento'),
        ),
        migrations.AlterField(
            model_name='storyslide',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='cor do fundo'),
        ),
    ]
