# Generated by Django 5.2.17 on 2026-09-21 12:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_storyelement_gap_alter_storyslide_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyelement',
            name='gap',
        ),
        migrations.AddField(
            model_name='storyelement',
            name='spacing_after_rem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o tamanho padrão de 0.4rem.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9.00'))], verbose_name='espaço abaixo do elemento (rem)'),
        ),
    ]
