# Generated by Django 5.2.17 on 2026-09-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_remove_storyelement_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyslide',
            name='image',
            field=models.ImageField(blank=True, upload_to='stories/slides/'),
        ),
    ]
