# Generated by Django 5.2.17 on 2026-10-02 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_affiliatelink_options'),
        ('stories', '0015_alter_storyslide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='affiliate_partner',
            field=models.ForeignKey(blank=True, help_text='Usado quando o elemento for um botão de afiliado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_elements', to='affiliates.affiliatelink', verbose_name='parceiro afiliado'),
        ),
    ]
