# Generated by Django 5.2.17 on 2026-10-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_alter_affiliatelink_options_and_more'),
        ('stories', '0016_alter_storyelement_affiliate_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyelement',
            old_name='affiliate_partner',
            new_name='affiliate_link',
        ),
    ]
