# Generated by Django 5.2.17 on 2026-10-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_alter_affiliatelink_options_and_more'),
        ('stories', '0017_remove_storyelement_affiliate_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='affiliate_link',
            field=models.ForeignKey(blank=True, help_text='Usado quando o elemento for um botão de link afiliado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_elements', to='affiliates.affiliatelink', verbose_name='link afiliado'),
        ),
    ]
