# Generated by Django 5.2.7 on 2025-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='net_tab',
        ),
        migrations.AddField(
            model_name='menulink',
            name='new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
