# Generated by Django 5.2.17 on 2026-08-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0008_alter_menulink_site_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('x-twitter', 'X / Twitter'), ('link', 'Outro')], default='instagram', max_length=20)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('new_tab', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('site_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Link social',
                'verbose_name_plural': 'Links sociais',
                'ordering': ('order', 'pk'),
            },
        ),
    ]
