# Generated by Django 5.2.17 on 2026-08-22 12:58

import site_setup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0009_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url_or_path',
            field=models.CharField(max_length=255, validators=[site_setup.validators.validate_menu_url]),
        ),
    ]
