# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0010_alter_menulink_url_or_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='placement',
            field=models.CharField(
                choices=[
                    ('both', 'Cabeçalho e rodapé'),
                    ('header', 'Somente cabeçalho'),
                    ('footer', 'Somente rodapé'),
                ],
                default='both',
                max_length=6,
                verbose_name='Exibir em',
            ),
        ),
    ]
