# Generated by Django 5.2

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0011_menulink_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='logo',
            field=models.ImageField(
                blank=True,
                default='',
                help_text='Envie o logo completo em PNG, de preferência com fundo transparente.',
                upload_to='assets/logo/%Y/%m/',
                validators=[utils.model_validators.validate_png],
                verbose_name='Logo do site',
            ),
        ),
    ]
