# Generated by Django 5.2.17 on 2026-08-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0012_sitesetup_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'Menu Link', 'verbose_name_plural': 'Menu Links'},
        ),
        migrations.AddField(
            model_name='menulink',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Números menores aparecem primeiro.', verbose_name='Ordem'),
        ),
    ]
