# Generated by Django 5.2.17 on 2026-08-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0013_alter_menulink_options_menulink_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Números menores aparecem primeiro.', verbose_name='Ordem')),
                ('site_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_sections', to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Categoria do rodapé',
                'verbose_name_plural': 'Categorias do rodapé',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='menulink',
            name='footer_section',
            field=models.ForeignKey(blank=True, help_text='Opcional. Links sem categoria aparecem em Explore.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='site_setup.footersection', verbose_name='Categoria do rodapé'),
        ),
        migrations.AddConstraint(
            model_name='footersection',
            constraint=models.UniqueConstraint(fields=('site_setup', 'title'), name='unique_footer_section_title_per_site'),
        ),
    ]
