# Generated by Django 5.2.17 on 2026-08-28 13:17

import site_setup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0014_footersection_menulink_footer_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='header_icon',
            field=models.FileField(blank=True, help_text='Opcional. Envie um SVG seguro de até 256 KB.', upload_to='assets/header-icons/%Y/%m/', validators=[site_setup.validators.validate_svg], verbose_name='Ícone do cabeçalho'),
        ),
    ]
