# Generated by Django 5.2.7 on 2025-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_at',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
