# Generated by Django 5.2.7 on 2025-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_update_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Este campo precisará estar marcado para o post ser exibido públicamente'),
        ),
    ]
