# Generated by Django 5.2.17 on 2026-08-22 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_author_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    AuthorProfile = apps.get_model('blog', 'AuthorProfile')

    AuthorProfile.objects.bulk_create(
        [AuthorProfile(user_id=user_id) for user_id in User.objects.values_list('pk', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_page_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Exibe este post antes dos demais nas listagens.'),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='', upload_to='authors/%Y/%m/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            create_existing_author_profiles,
            migrations.RunPython.noop,
        ),
    ]
