# Generated by Django 5.2.17 on 2026-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_excerpt_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legenda da capa'),
        ),
    ]
