# Generated by Django 5.2.17 on 2026-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, default='', upload_to='categories/%Y/%m/', verbose_name='Imagem da capa da categoria'),
        ),
    ]
