# Generated by Django 5.2.17 on 2026-08-28 16:57

import affiliates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de afiliado',
                'verbose_name_plural': 'categorias de afiliados',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(max_length=400, validators=[affiliates.models.validate_plain_text], verbose_name='descrição')),
                ('image', models.ImageField(upload_to='affiliates/%Y/%m/', verbose_name='imagem')),
                ('image_alt', models.CharField(max_length=150, verbose_name='texto alternativo da imagem')),
                ('affiliate_url', models.URLField(max_length=1000, validators=[affiliates.models.validate_https_url], verbose_name='link de afiliado')),
                ('button_label', models.CharField(default='Conhecer parceiro', max_length=40, verbose_name='texto do botão')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='affiliates.affiliatecategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'parceiro afiliado',
                'verbose_name_plural': 'parceiros afiliados',
                'ordering': ('order', 'name'),
            },
        ),
    ]
