# Generated by Django 5.2.17 on 2026-08-28 19:35

import site_setup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecategory',
            name='icon',
            field=models.FileField(blank=True, help_text='Opcional. Envie um SVG seguro de até 256 KB.', upload_to='affiliates/category-icons/%Y/%m/', validators=[site_setup.validators.validate_svg], verbose_name='ícone'),
        ),
    ]
