# Generated by Django 5.2.17 on 2026-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_affiliatecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepartner',
            name='cta_icon',
            field=models.ImageField(blank=True, editable=False, upload_to='affiliates/cta-icons/%Y/%m/', verbose_name='ícone do CTA'),
        ),
    ]
