# Generated by Django 5.2.17 on 2026-10-02 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_affiliatepartner_cta_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, help_text='Explique o link e em quais temas ele pode ser recomendado.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='affiliates.affiliatepartner', verbose_name='links dos afiliados')),
            ],
        ),
    ]
