# Generated by Django 5.2.17 on 2026-10-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_affiliatelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatelink',
            options={'ordering': ('created_at', 'updated_at'), 'verbose_name': ('link afiliado',), 'verbose_name_plural': 'links afiliados'},
        ),
    ]
