# Generated by Django 5.2.17 on 2026-10-02 19:00

import affiliates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_affiliatelink_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatelink',
            options={'ordering': ('affiliate_partner', 'name'), 'verbose_name': 'link afiliado', 'verbose_name_plural': 'links afiliados'},
        ),
        migrations.RemoveField(
            model_name='affiliatepartner',
            name='affiliate_url',
        ),
        migrations.RemoveField(
            model_name='affiliatepartner',
            name='button_label',
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='affiliate_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='affiliates.affiliatepartner', verbose_name='parceiro afiliado'),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='description',
            field=models.TextField(blank=True, help_text='Explique em quais temas o link pode ser recomendado.', max_length=300, validators=[affiliates.models.validate_plain_text], verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='url',
            field=models.URLField(max_length=1000, validators=[affiliates.models.validate_https_url], verbose_name='URL do link'),
        ),
    ]
