# Generated by Django 5.2.17 on 2026-10-02

import affiliates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_alter_affiliatelink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepartner',
            name='affiliate_url',
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[affiliates.models.validate_https_url],
                verbose_name='link principal de afiliado',
            ),
        ),
        migrations.AddField(
            model_name='affiliatepartner',
            name='button_label',
            field=models.CharField(
                default='Conhecer parceiro',
                max_length=40,
                verbose_name='texto do botão',
            ),
        ),
    ]
